
package fr.khady.wsbiblio.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BibliothequeException", targetNamespace = "http://webService.wsBiblio.khady.fr/")
public class BibliothequeException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BibliothequeFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BibliothequeException(String message, BibliothequeFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BibliothequeException(String message, BibliothequeFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fr.khady.wsbiblio.webservice.BibliothequeFault
     */
    public BibliothequeFault getFaultInfo() {
        return faultInfo;
    }

}
